name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: License Action
      uses: dephraiim/license-action@v0.1.2
      with:
        LICENSE_TYPE: MIT
        AUTHOR: Ephraim Atta-Duncan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_WORKSPACE: ${{ secrets.GITHUB_WORKSPACE }} 
