name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Adding License
      uses: dephraiim/license-action@v0.1.13
      with:
        LICENSE_TYPE: Unlicense
        AUTHOR: Ephraim Atta-Duncan
